"""migration

Revision ID: 19478ffa3cf5
Revises: 7bb48ecfe1b2
Create Date: 2024-03-15 20:58:41.643132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19478ffa3cf5'
down_revision: Union[str, None] = '7bb48ecfe1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_threads_id', table_name='threads')
    op.drop_index('ix_threads_thread_id', table_name='threads')
    op.drop_index('ix_threads_user_id', table_name='threads')
    op.drop_table('threads')
    op.drop_index('ix_bans_id', table_name='bans')
    op.drop_index('ix_bans_user_id', table_name='bans')
    op.drop_table('bans')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('is_shadow', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bans_user_id', 'bans', ['user_id'], unique=False)
    op.create_index('ix_bans_id', 'bans', ['id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('thread_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threads_user_id', 'threads', ['user_id'], unique=False)
    op.create_index('ix_threads_thread_id', 'threads', ['thread_id'], unique=False)
    op.create_index('ix_threads_id', 'threads', ['id'], unique=False)
    # ### end Alembic commands ###
