"""migration

Revision ID: 20af4b7bf632
Revises: 9f28ff2f0312
Create Date: 2024-05-29 21:07:56.497986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20af4b7bf632'
down_revision: Union[str, None] = '9f28ff2f0312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tgusers', sa.Column('subject', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tgusers', 'subject')
    # ### end Alembic commands ###
