"""migration

Revision ID: 351b0094e698
Revises: 19478ffa3cf5
Create Date: 2024-04-24 17:40:44.509551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351b0094e698'
down_revision: Union[str, None] = '19478ffa3cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tgusers', sa.Column('last_user_msg_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tgusers', 'last_user_msg_at')
    # ### end Alembic commands ###
