"""migration

Revision ID: 465cfc43f9f7
Revises: 5d9ebc5b2cee
Create Date: 2025-03-08 20:49:19.395105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465cfc43f9f7'
down_revision: Union[str, None] = '5d9ebc5b2cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tgusers', sa.Column('first_replied', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.drop_column('tgusers', 'shadow_banned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tgusers', sa.Column('shadow_banned', sa.BOOLEAN(), nullable=False))
    op.drop_column('tgusers', 'first_replied')
    # ### end Alembic commands ###
