"""migration

Revision ID: 7bb48ecfe1b2
Revises: c199c3598bc6
Create Date: 2024-03-15 20:55:49.174340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '7bb48ecfe1b2'
down_revision: Union[str, None] = 'c199c3598bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tgusers = op.create_table('tgusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=129), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.Column('shadow_banned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tgusers_id'), 'tgusers', ['id'], unique=False)
    op.create_index(op.f('ix_tgusers_thread_id'), 'tgusers', ['thread_id'], unique=False)
    op.create_index(op.f('ix_tgusers_user_id'), 'tgusers', ['user_id'], unique=False)

    # Added manually. Move data from the old table Threads to the new table TgUsers
    conn = op.get_bind()
    res = conn.execute(text("select user_id, thread_id from threads"))
    results = res.fetchall()
    rows = [{'user_id': r[0], 'thread_id': r[1], 'banned': False, 'shadow_banned': False}
            for r in results]
    op.bulk_insert(tgusers, rows)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tgusers_user_id'), table_name='tgusers')
    op.drop_index(op.f('ix_tgusers_thread_id'), table_name='tgusers')
    op.drop_index(op.f('ix_tgusers_id'), table_name='tgusers')
    op.drop_table('tgusers')
    # ### end Alembic commands ###
