"""migration

Revision ID: 9f28ff2f0312
Revises: 351b0094e698
Create Date: 2024-05-11 12:35:46.648113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f28ff2f0312'
down_revision: Union[str, None] = '351b0094e698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actionstats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('new_user', 'user_message', name='actionname'), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actionstats')
    # ### end Alembic commands ###
